### ISSUE TITLE
Bug Handling Trailing Zeroes with icd9ExplainDecimal()

### ISSUE THREAD

**Issue by sgfin** [jackwasey/icd#109]
It appears that icd9ExplainDecimal() sometimes returns bizarre and unexpected values when provided with a code that lacks a trailing zero.  This strikes me as particularly dangerous, because icd9ExpandRange() produces such values.

Example:
```
# Returns "Generalized convulsive epilepsy, without mention of intractable epilepsy" -- CORRECT
print(icd9ExplainDecimal("345.10"))

# Returns "Nystagmus, unspecified" -- INCORRECT
print(icd9ExplainDecimal("345.1"))

# Returns "Nystagmus, unspecified" -- CORRECT
print(icd9ExplainDecimal("379.50"))
```

**Comment by jackwasey** [comment]
Thanks for picking up on that.

It would be most helpful if you could frame your examples (both successes and failures) as testthat tests, and make a pull request to include them. Numerous examples in the `tests` sub-directory. I will certainly look into this, but if you are able to debug at all, it would speed up resolution. Thanks, Jack.

**Comment by samfin55** [comment]
OK, will try to do this.  In the meantime, for posterity, be aware that it appears to be more than a simple trailing zero problem:

![image](https://cloud.githubusercontent.com/assets/2760120/20869578/4e013aae-ba43-11e6-8d94-dba249fbc90a.png)

**Comment by jackwasey** [comment]
Hmm. I see in:
http://www.icd9data.com/2012/Volume1/320-389/340-349/345/345.2.htm
that `345.20` is undefined. In searching co-morbidities I am generous in accepting this by inferring the intended code belongs to the parent. However, strictly, there is no explanation for `345.20`.
In the current github version of `icd` I get:
```
> icd_explain("345.20")
character(0)
Warning message:
Some ICD codes are not 'defined' when trying to condense when explaining codes.
              Will drop these and continue. E.g. 34520 
```

You are indeed correct that code `345.1` was parsed incorrectly from the RTF canonical source, and I will do something about this. A small number of these have slipped through the parsing. Unfortunately there is no good public machine readable source of ICD-9-CM data.
