### ISSUE TITLE
Help Using the icd_comorbid_quan_elix function in icd

### ISSUE THREAD

**Issue by slakkur1** [jackwasey/icd#110]
Let's say that I have the following data frame: 
mydf <- data.frame(visit_name = c("a"),icd9 = c("I22.2"))

Now I expect patient 'a' to get an Elixhauser score of 7 based on the first attached document (vanWalravenQuanElixScore, page 3) and second attached document (ElixQuanPaper, page 5).

When I do the following:
icd_comorbid_quan_elix(mydf)

the "CHF" category is false, when I think it should be true. Any suggestions?

Also is there an equivalent to the "icd9VanWalravenComorbid" function in the icd package. That was the function name in the icd9 package.

[vanWalravenQuanElixScore.pdf](https://github.com/jackwasey/icd/files/647398/vanWalravenQuanElixScore.pdf)
[ElixQuanPaper.pdf](https://github.com/jackwasey/icd/files/647402/ElixQuanPaper.pdf)

**Comment by jackwasey** [comment]
Thanks for the report. It's very helpful to have feedback like this. My goal in creating the package was to algorithmically extract data from the source ICD data and original SAS code, to be as close as possible to the original intent of the authors. I think this is the most reproducible approach, but does produce the odd mistake.

Two things would be helpful:
1. Write a `testthat` test cases specifically for this anomaly. It would be three or four lines of code, and there are numerous examples in the icd/tests directory.
2. Look into it! The logic for calculating those scores is quite simple. It may be that the ICD code was interpreted incorrectly (which would be another testthat test case...) or the logic could be wrong.

One quick thing I notice is that you have an ICD-9 column name in your data frame, with an ICD-10 code in it. When there is just one code, and without specifying ICD-9 vs ICD-10, `icd` guesses the type. I don't see why it would get I122.2 wrong, but it is possibly the source of your error.

**Comment by slakkur1** [comment]
It turns out I22.2 is a billable code which is why I got a value of zero. It works if I do 
mydf <- data.frame(visit_name = c("a"),icds = c("I09.9"))
cmbtest <- icd_comorbid_quan_elix(mydf)
elix_score<-icd9VanWalravenComorbid(cmbtest)

I get the correct answer of 7.

It does not work if I use an icd9 and an icd10 code in the same dataframe. The answer to the code below should be 6, but I get -1. It seems like only the icd9 code is being recognized (that gives the score of -1) but the icd10 code is not being recognized (that would give a 7, making the total elixhauser score 6). Is there an extra column that needs to be specified in the data frame distinguishing the icd9 and icd10 codes, or is the "as.icd9" and "as.icd10" functions enough?

mydf <- data.frame(visit_name = c("a","a"),icds = c(as.icd9("394.0"),as.icd10("I09.9")))
cmbtest <- icd_comorbid_quan_elix(mydf)
elix_score<-icd9VanWalravenComorbid(cmbtest)

**Comment by jackwasey** [comment]
You're right: you can't mix icd9 and icd10 codes in one column.

A good workaround is to calculate the comorbidities for your ICD-9 and ICD-10 codes independently, combine those, then calculate the scores. E.g.

```
icd10 <- data.frame(pts = c("A", "A"), c("C82.28", "M08.979"))
icd9 <- data.frame(pts = c("A", "A"), c("041.04", "244.9"))
both <- comorbid_elix(icd9) + comorbid_elix(icd10)
van_walraven_from_comorbid(both)
```
