### ISSUE TITLE
ICD9 AHRQ CHF Extra Codes

### ISSUE THREAD

**Issue by nohammar** [jackwasey/icd#112]
From the SAS code found here https://www.hcup-us.ahrq.gov/toolssoftware/comorbidity/comformat2012-2015.txt, CHF should be 

 "39891", "4280 "-"4289 " = "CHF" 

but icd9_map_ahrq$CHF also includes "40201" "40211" "40291" "40401" "40403" "40411" "40413" "40491" "40493"

**Comment by jackwasey** [comment]
I'll look into it at some point. I did include the SAS code I used in the
github repo (and maybe package itself?) and a reference to the primary
literature. Also:
http://www.icd9data.com/2012/Volume1/390-459/401-405/402/402.01.htm
(Malignant hypertensive heart disease with heart failure)

i.e. heart failure is explicit in the diagnosis, so this seems a reasonable
inclusion.

**Comment by nohammar** [comment]
Thanks yeah I don't disagree that the inclusion is reasonable, but I think the AHRQ version should match the official AHRQ version which they use to calculate their comorbs as well as provide the software to do so. I had to hunt to find why my comorbidity rates were different using this package than when using AHRQ's official version and this turned out to be the biggest difference.

**Comment by aalexandersson** [comment]
I agree with nohammar. You can still create an improved or enhanced AHRQ-like version or your own mix-and-match version with a descriptive label such as "AHRQi" or "AHRQe" or "Wasey".

**Comment by jackwasey** [comment]
Okay, the 'icd' implementation does match AHRQ. The format file you reference contains several subcategories of hypertension. The other SAS file `comoanaly2012-2013.txt` processes these, and generates the full list of HTN diagnoses. This is reflected in the pre-processing done by 'icd' to regenerate the mapping.

**Comment by aalexandersson** [comment]
So you are now using DRG? If not, how can the 'icd' implementation match AHRQ?

**Comment by jackwasey** [comment]
The code published by AHRQ is by Quan, and has both DRG and Elixhauser comorbidity groupings. I just reimplemented the Elixhauser part of the code in R (by actually interpreting the original SAS code). I did not use the DRG portion of that SAS format file.
