### ISSUE TITLE
icd_explain("7806") returns wrong results

### ISSUE THREAD

**Issue by iacobus42** [jackwasey/icd#115]
icd_explain() returns the wrong results with "7806"

    > icd_explain("7806")
    [1] "Mechanical complication of respirator [ventilator]"

when it should return "Fever and other psychological disturbances of temperature regulation".

However, running `icd_explain()` on the sub-codes (e.g., 780.61) produces the correct label

    > icd_explain("78061")
    [1] "Fever presenting with conditions classified elsewhere"

This might be similar to #111 and #113

**Comment by jackwasey** [comment]
Thanks for reporting. Are neighboring codes similarly affected?

The ICD-9 parsing code is already so complicated, so I'm resolving these occasional slips by adding exceptions in the generation code.
