### ISSUE TITLE
Description missing for ICD-10 "W02"

### ISSUE THREAD

**Issue by hans-ekbrand** [jackwasey/icd#116]
icd_explain("W02")
    character(0)

The canonical answer is "Fall involving ice-skates, skis, roller-skates or skateboards", see http://apps.who.int/classifications/icd10/browse/2010/en#/W00-W19.

**Comment by jackwasey** [comment]
Thanks for the report. Parsing quirk. Will likely add an exception. note that ICD-10 WHO asserts copyright, so I have included the public domain (and mostly more detailed) ICD-10-CM from the USA. W02 is the same in both systems.

**Comment by jackwasey** [comment]
Hmm. The official source at http://www.cdc.gov/nchs/data/icd/icd10cm/2016/ICD10CM_FY2016_code_descriptions.zip doesn't include "W02" This is still an ICD-10 code from the WHO, but unbelievably, WHO asserts copyright so I can't include it directly in the package.

ICD-10-CM had W02, but it was deactivated.

I am looking for a work-around to the ICD-10 copyright issue, perhaps one that can be used also for other copyrighted encodings, like CPT. It will probably involve downloading the raw data on a per-user basis once on installation of the package, but currently don't have the time to work on this. Is someone interested in doing this?

Reluctantly closing as it doesn't apply to ICD-10-CM, but would love to solve this problem more generally in the future.
