### ISSUE TITLE
negative scores

### ISSUE THREAD

**Issue by rpietro** [jackwasey/icd#121]
This is not an issue but more of a clarification: In this paper http://czresearch.com/dropbox/vanWalraven_MedCare_2009v47p626.pdf I see that Elixhauser's scores can be negative, but I couldn't find a reason why. I am currently getting negative scores from an analysis using the ICD package applied to MEPS data https://meps.ahrq.gov/mepsweb/ and having a hard time making sense of it even after looking at the code calculatiing the algorithm. 

Could you help me understand how this can be interpreted? I can send a reproducible example if necessary.

**Comment by lucasxteixeira** [comment]
+1
Here is a reproducible example of a single observation from MEPS that returns a negative value:

`data <- data.frame(
  DUPERSID = rep("40043102", 12),
  ICD9CODX = c("401", "414", "272", "173", "372", "311", "173", "-1", "300", "V72", "110", "332", "787", "-9")
)

icd::icd_van_walraven(data, visit_name = "DUPERSID", icd_name = "ICD9CODX")`

**Comment by jackwasey** [comment]
thanks for comments and example. will take a look.

**Comment by jackwasey** [comment]
A working reprex:
```
data <- data.frame(
  DUPERSID = rep("40043102", 14),
  ICD9CODX = c("401", "414", "272", "173", "372", "311", "173", "-1", "300", "V72", "110", "332", "787", "-9")
)
icd::icd_van_walraven(data)
```

**Comment by jackwasey** [comment]
This code gives -3
```
data <- data.frame(DUPERSID = "40043102", ICD9CODX = c("311"))
icd::icd_van_walraven(data)
icd_explain("313")
[1] "Disturbance of emotions specific to childhood and adolescence"
```

And in the paper we both cite, "Depression" has a weight of -3 for in-hospital mortality.
