### ISSUE TITLE
icd9::icd9Explain and icd::icd_explain do not appear to agree

### ISSUE THREAD

**Issue by mbcann01** [jackwasey/icd#123]
Hello,

I recently switched from using the icd9 package to the icd package. I noticed that I'm now getting some unexpected results. For example:

`icd9::icd9Explain("681.1")` returns "Toe"
`icd::icd_explain("681.1")` returns "Sacroiliac ligament"

`icd9::icd9Explain("786.5")` returns "Chest pain"
`icd::icd_explain("786.5")` returns "Aftercare for healing pathologic fracture of leg, unspecified"

And there are others.

When I do a quick Google search, it appears as though the description given by icd9::icd9Explain() is the correct description. I also tried using the `icd::as.icd9` and `icd::as.icd9cm` helper functions - to the same result.

Just wondering if this is a bug, or something I'm doing incorrectly? Many thanks!

**Comment by jackwasey** [comment]
Thanks for that. `icd` used a different parsing mechanism from the (non-machine-readable) ICD-9-CM documentation RDF file. This isn't perfect, and I'm afraid occasional errors appear like this. See also #124 and others. Quick to fix, and please let me know any more you notice.

**Comment by mbcann01** [comment]
No problem, Jack. Here is a full list of the icd9 codes that didn't agree for me. As you can see, some are just not in agreement because of missing commas and things like that. However, others are very different. Hope this helps.

[not_agree.xlsx](https://github.com/jackwasey/icd/files/1113404/not_agree.xlsx)
