### ISSUE TITLE
icd_explain example results

### ISSUE THREAD

**Issue by mkim0710** [jackwasey/icd#124]
Hi, thanks for maintaining this great library.

I was following the tutorial.

https://cran.r-project.org/web/packages/icd/vignettes/introduction.html

I do not understand the following examples. Are they what they are supposed to be? (i.e. "Retinopathy of prematurity, stage 1"?) 

# icd_explain summarizes these to just two groups:
icd9_map_quan_deyo[["Dementia"]] %>% icd_explain(warn = FALSE)
#> [1] "Dementias"                          
#> [2] "Retinopathy of prematurity, stage 1"
#> [3] "Senile degeneration of brain"
# contrast with:
icd9_map_quan_deyo[["Dementia"]] %>% icd_explain(condense = TRUE, warn = FALSE)
#> [1] "Dementias"                          
#> [2] "Retinopathy of prematurity, stage 1"
#> [3] "Senile degeneration of brain"

If these results are erroneous, please let me know your advice how I may resolve this.

Thanks.

-m

**Comment by jackwasey** [comment]
Hi, thanks for the report. Unfortunately there is no good machine readable source of the codes, and the parsing has the occasional glitch: this looks like one of them. These are one-line fixes: you might want to install from `devtools::install_github("jackwasey/icd")` once I do this, as there won't be a new CRAN release for a little while.

**Comment by mkim0710** [comment]
Thanks again for maintaining this library.

**Comment by jackwasey** [comment]
The function `icd9cm_hierarchy_hotfix` in R/parse.R contains the exceptions to the parsing. Would you consider submitting a pull request to add the relevant codes?
