### ISSUE TITLE
mismatch of codes and descriptions

### ISSUE THREAD

**Issue by ababayan13** [jackwasey/icd#126]
I noticed errors on some codes, not sure how widely spread it is:
Please check icd9 codes. Here are 2 sample errors:
_291 Flat retinoschisis_
should be  _Alcohol-induced mental disorders_

similar issue is observed with 361
_361 Rheumatic fever with heart involvement_ 
should be _Retinal detachments and defects_

majors, chapters, sub_chapters are correct the mapping in hierarchy file has issues

**Comment by jackwasey** [comment]
Thanks for the report. As there is no canonical machine readable source of ICD-9 codes, the icd package parses an RTF file, which does occasionally make these bizarre mistakes.

The function `icd9cm_hierarchy_hotfix` in R/parse.R contains the exceptions to the parsing. You might consider submitting a pull request to add the relevant codes.
