### ISSUE TITLE
CMSHCC_MAP and List for ICD10

### ISSUE THREAD

**Issue by nandya** [jackwasey/icd#129]
I am trying to calculate HCC for both ICD9 and 10, comorbidity function is available for both 9 and 10 but the data file for List and Map is available for icd9 only, couldnt find the icd10 mapping.

Is the mapping already available?

Thanks for your help.

Aloke

**Comment by jackwasey** [comment]
`icd10_comorbid_hcc` and this is called automatically by `icd_comorbid_hcc` if you give it ICD-10 codes.

**Comment by jackwasey** [comment]
`comorbid_hcc` from `icd` version 3 onwards, but `icd_comorbid_hcc` will still work.
