### ISSUE TITLE
Question on how to apply icd9_map_cc function

### ISSUE THREAD

**Issue by ekortemeier** [jackwasey/icd#132]
Hello! I reached out to Dr. Wasey about this, but am hoping to get input here as well -- Dr. Wasey mentioned @anobel might have advice.

I was wondering if there is an example of how to use the icd9_map_cc function (or icd10). I am able to run it and get the dataframe containing the icd code, the condition category, and the year, as mentioned in the documentation, but I am not sure how to proceed. Is it possible to apply this to person and diagnosis data (like the CMS SAS approach) and obtain an HCC score or risk score? Any guidance would be much appreciated. 

Thanks!
Emma Kortemeier

**Comment by jackwasey** [comment]
This is documented in the vignette, [Using Hierarchical Condition Codes](https://jackwasey.github.io/icd/articles/Using_Hierarchical_Condition_Codes.html). Of note, `icd9_map_cc` is data: the function to use is `comorbid_hcc`. `?comorbid_hcc` gives some more detail.
