### ISSUE TITLE
icd10_comorbid crashes on more than a few rows

### ISSUE THREAD

**Issue by olgapierce** [jackwasey/icd#133]
Hi Jack,

I love your icd package! It's been a lifesaver, especially since we're a journalism non-profit and SAS isn't really an option for us.  We've used the package for award-winning stories about topics like health care disparities and maternal mortality.

I'm writing because I've been having some difficulty with comorbidity mapping in ICD10. 

I'm using Medicare administrative data, with about 50 diagnosis fields per claim number. I've successfully comorbidity mapped millions of rows of ICD-9 claims using your package with no issues.

ICD-10 has been giving me a bit of a hard time though.

When I run this:

df <- data_2015_10_test_long %>% gather(diag_field,icd10,-CLAIMNO)

df <- data_2015_10_test_long %>% arrange(CLAIMNO)
data_diag_elix_test_m <- icd_long_data(df)

data_diag_elix_test <- icd10_comorbid(data_diag_elix_test_m, icd10_map_ahrq, visit_name = 'CLAIMNO', icd_name = 'icd10', aggregate = FALSE)

on one to six rows, it goes lickety split. But if I run it on 7 or more rows, it crashes R almost immediately. I don't think it's computing power -- I'm working on a pretty big amazon instance with 200 GB of RAM.

I've attached a text file with data that resembles some from our set. 

Thanks again for helping us out!

Olga
[tiny_slice.txt](https://github.com/jackwasey/icd/files/1757419/tiny_slice.txt)

**Comment by jackwasey** [comment]
I pushed a temporary fix: the problem was ICD-10 codes shorter than 3 characters (which are always invalid). The current master branch aborts without segfault if this condition occurs. It should just ignore such a code, which will be the next step.

https://github.com/jackwasey/icd/commit/edcdf8ab18fba0d870bb240c9a1ce11b1d522853
I mistakenly stated the patch fixed issue 138, not 133, so linking here properly now.

**Comment by jackwasey** [comment]
Now fixed properly - it'll skip invalid codes and not just abort to avoid the segfault.

**Comment by jackwasey** [comment]
The workaround, if you don't want to install from github or wait for CRAN release, is to ensure all ICD-10 codes are at least three characters.

**Comment by olgapierce** [comment]
Hi Jack –

This help is great. So, if an ICD-10 code is not three characters, does it just stop?

Would it then be useful for me screen out invalid codes ahead of time? I have tens of millions of rows, so I just need to make sure it will work at scale.

Thanks again!

O
