### ISSUE TITLE
add 2017 hierarchical condition codes

### ISSUE THREAD

**Issue by jackwasey** [jackwasey/icd#134]
@anobel perhaps you could add this? I see the neatly arrayed files in data-raw, but it looks like you did some pre-processing work to get to this point.

Note I am making a minor change to the HCC parsing code, because the HCC table has "icd_name" as a column name: this is used everywhere else as a variable name which contains the column name. I therefore changed it to "icd_code" so `icd_name <- "icd_code"`

Similar issue with visit_name in the HCC comorbidity calculations.

This may be a breaking change: if so, I'd welcome your suggestions on how to deal with this.

**Comment by anobel** [comment]
Will get working on it!

**Comment by jackwasey** [comment]
fixed by 2ad4807dce94e14eaeddaa15c79bcd16981bff9c
