### ISSUE TITLE
icd_comorbid_hcc parameter icd_name issues

### ISSUE THREAD

**Issue by wayneking04** [jackwasey/icd#140]
When merging data with icd:icd9_map_cc, the column name for icd codes in the data have to be the same as icd:icd9_map_cc. Different versions of the cd:icd9_map_cc have different names (either 'icd_code' or 'icd_name'). When the data have a different icd column name, this will cause the merge to only on 'year', therefore merge all ccs for that year.

**Comment by jackwasey** [comment]
Thanks - will look into this. Would you be able to write a very short reproducible example?

**Comment by jackwasey** [comment]
@anobel  is this something you could take a look at?

**Comment by jackwasey** [comment]
@wayneking04 would you please provide us with a short reproducible example?
