### ISSUE TITLE
Pushing computation into a database

### ISSUE THREAD

**Issue by ablack3** [jackwasey/icd#148]
Would there be any interest in making this package work with tbl_dbi database connection object defined by dplyr? 

I have been doing similar work using dplyr to send SQL to a really fast database.  Writing functions that use dplyr to generate SQL and push computation into an optimized database is an intriguing idea, particularly with large datasets like claims data. However this might be too big of a change to be feasable for the icd package.

**Comment by jackwasey** [comment]
Yes, I've heard from a biostatistician recently thinking about this possibility. It's not something I've done before, contributions in this area welcome.

It may however be a false economy: string matching even in a fast SQL database may well be slower than the current icd algorithm which turns it into an integer matrix multiplication problem, which is highly optimized on most platforms, especially massively multicore servers. It may still be quicker to extract a big table to (big server) RAM and compute with icd. String matching just takes a lot of CPU cycles and more CPU cache churn. Benchmarks would tell.

The other issue is that there are so many quirks when you get down to the real computation, so I doubt the SQL was be simple. It may even be too complex to generate the SQL via `dplyr`.
