### ISSUE TITLE
icd_comrobid_hcc input structure flexibilty  

### ISSUE THREAD

**Issue by kcoyle-US** [jackwasey/icd#153]
When utilizing the icd_cormobid_hcc function on the following data set 
[ClaimsFileHEE_s125.xlsx](https://github.com/jackwasey/icd/files/2142108/ClaimsFileHEE_s125.xlsx)

```
library(icd)
library(icd.data)
library(LaF)
library(dplyr)

#Opening connection to data file 
df<- laf_open_csv(".../ClaimsFileHEE_s125.csv",
                  column_types = c("character","string" ,"character","character","character","character","character"), 
                  column_names = c("date",     "visit_id",     "ICD1",     "ICD2",     "ICD3",     "ICD4",     "ICD5"), 
                  skip = 1)

#small test sample of 4 rows type: data.frame
y <-next_block(x = df, nrows=4)
test<- wide_to_long(y,visit_name = "visit_id",icd_name = "icd_code",icd_regex  = c("ICD","icd", "diag"))
test$date<-as.Date(test$date)
test<-icd_comorbid_hcc(test,date_name = "date",visit_name = "visit_id",icd_name = "icd_code")

```

the resulting error is displayed
``
Error in `$<-.data.frame`(`*tmp*`, "todrop", value = TRUE) : 
  replacement has 1 row, data has 0
``
any suggestions on how to change the input to fit the structure of the examples provided by the package author ?

**Comment by jackwasey** [comment]
The replication code you provided didn't quite work, e.g. as.Date needed a format, and an extra heading row needed removal. After that, I realized you had a mixture of ICD-9 and ICD-10 codes.

I'm not so familiar with HCC. I get good looking results when I use the subset of lines which are from ICD-9 codes. As there are overlaps between ICD-9 and ICD-10 code names (e.g. V10), `icd` doesn't work with a mixed set of codes: you'll need to define which are which and call the HCC function twice. Hope this helps: let me know how it goes. Thanks for the report.

**Comment by jackwasey** [comment]
Oh, and yes you did find a big when there are no NAs returned internally to the HCC function - thanks for that, too. I am committing a fix now, so you will be able to use `install_github("jackwasey/icd")` until it makes it to CRAN.

**Comment by jackwasey** [comment]
PS: this is the simpler replication code:
```
library(icd)
library(LaF)
#Opening connection to data file 
df<- laf_open_csv("/Users/waseyj/Downloads/ClaimsFileHEE_s125.csv",
                  column_types = c("character","string" ,"character","character","character","character","character"), 
                  column_names = c("date",     "visit_id",     "ICD1",     "ICD2",     "ICD3",     "ICD4",     "ICD5"), 
                  skip = 1)

#small test sample of 4 rows type: data.frame
y <- next_block(x = df, nrows=4)[-1, ]
test <- wide_to_long(y, icd_regex  = c("ICD","icd", "diag"))
test$date <-as.Date(test$date, format = "%m/%d/%y")
dput(test[1:4, ])
test <-icd_comorbid_hcc(test)
```
