### ISSUE TITLE
checkmate bug fix breaks unit test

### ISSUE THREAD

**Issue by mllg** [jackwasey/icd#160]
I've recently discovered and fixed a bug w.r.t. missing checks in lists in https://github.com/mllg/checkmate/issues/146. The bugfix now tests lists for elements being identical to `NULL` which comes closest to a "missing" in lists, but this unfortunately breaks a unit test in your package. Before the fix, the test was defunct and did not trigger any check at all. 

Could you please check your assertions accordingly with the devel release of checkmate? I'll prepare a new release of checkmate and will upload checkmate after icd has been released to CRAN.

Sorry for the inconvenience.

**Comment by jackwasey** [comment]
Thanks for letting me know. Fixed committed, and will get to CRAN soon.

**Comment by mllg** [comment]
Any updates?

**Comment by jackwasey** [comment]
Tidying a few other things up. Should be able to release today or within coming few days.
