### ISSUE TITLE
Missing comorbidity category in 'icd10_comorbid_quan_elix'

### ISSUE THREAD

**Issue by RockinRichi** [jackwasey/icd#162]
Hello,

when determining comorbidities by 'icd10_comorbid_quan_elix' the category HTNcx (Hypertension, complicated) is not assessed properly. Reproducing:

**1. In principal this category is stored properly in the quan_elix map:**
```r
library(icd)

a <- icd10_map_quan_elix
a[['HTNcx']]
```

**2. However when applied to patient data, the HTNcx category is missing:**
```r
b <- data.frame(id = 1, code = 'F101')
c <- icd10_comorbid_quan_elix(b, icd_name = 'code', return_df = TRUE)
c   # contains no HTNcx column
c$HTNcx  # is NULL, but should be FALSE
```

Best Regards.

**Comment by jackwasey** [comment]
Thanks for reporting. Actually, this is intended behavior, following the intention of the source publication. To get what you want, you can add `hierarchy = FALSE` to not wrap up hypertension with complications into plain hypertension. Similar rules apply for the various comorbidity maps. Try:
```
c <- icd10_comorbid_quan_elix(b, icd_name = 'code', return_df = TRUE, hierarchy = FALSE)
c$HTNcx # now FALSE
```

**Comment by jackwasey** [comment]
PS, note that you can drop the `icd_name` argument, since `icd` will guess which column to use based on name and content.
```
c <- icd10_comorbid_quan_elix(b, return_df = TRUE, hierarchy = FALSE)
c$HTNcx # now FALSE
```

**Comment by RockinRichi** [comment]
Ah, thanks for your explanation.
