### ISSUE TITLE
icd 9 health care claim prediction 

### ISSUE THREAD

**Issue by vgramu** [jackwasey/icd#164]
DiagnosisGroupCode | ClmDiagnosisCode_1 | ClmDiagnosisCode_2 | ClmDiagnosisCode_3 | ClmDiagnosisCode_4 | ClmDiagnosisCode_5 | ClmDiagnosisCode_6 | ClmDiagnosisCode_7 | ClmDiagnosisCode_8 | ClmDiagnosisCode_9
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
201 | 1970 | 4019 | 5853 | 7843 | 2768 | 71590 | 2724 | 19889 | 5849
750 | 6186 | 2948 | 56400 | NA | NA | NA | NA | NA | NA
883 | 29623 | 30390 | 71690 | 34590 | V1581 | 32723 | NA | NA | NA
67 | 43491 | 2762 | 7843 | 32723 | V1041 | 4254 | 25062 | 40390 | 4019
975 | 42 | 3051 | 34400 | 5856 | 42732 | 486 | 5119 | 29620 | 20300
597 | 1745 | V4571 | 78702 | 28521 | 7019 | 1963 | 2948 | 25000 | 25002
390 | 1536 | 73300 | 7230 | 3659 | 2859 | 4019 | 2948 | 2809 | 56210
379 | 56212 | 25000 | 30000 | 73300 | 2766 | 53081 | 2851 | 4439 | 41401
294 | 42823 | 4280 | 6822 | 40390 | 43811 | 78322 | NA | NA | NA

**Comment by jackwasey** [comment]
Please do elaborate...

**Comment by jackwasey** [comment]
There are too many different ICD codes to use them directly as features in a meaningful machine learning model. You could use one of the functions in 'icd', e.g. 'comorbid_ahrq' to reduce the problem space to the categories of diseases. This would also lose a lot of information, as we have no idea whether fraudulent claims would have features which crossed comorbidity boundaries. You might do some NLP on the descriptions (in `icd.data` package), or work with the intrinsic hierarchy of ICD codes to reduce the feature space e.g. 441 is 'parent' to 441.0 - 'icd' has functions to navigate this hierarchy. Up-coding (coding a more serious condition than really existed) is a common problem, and may be related to the last point. That's as far as ICD specifically can help, I'm afraid: this is primarily a machine learning problem, not a comorbidities or ICD coding issue.
