### ISSUE TITLE
Why are some ICD 10 codes not defined?

### ISSUE THREAD

**Issue by ablack3** [jackwasey/icd#169]
I am working with ICD 10 codes on death certificate data. Some of the cause of death codes on the death certificates are not defined according to the icd package. I'm just wondering if I am missing something.

For example `is_defined(as.icd10("I21.9"))` returns `FALSE`. It seems to me like "I21.9" should be a CMS defined code.

Thanks for this incredibly helpful package.

**Comment by jackwasey** [comment]
Thanks for the report. That code was added in 2018 https://www.icd10data.com/ICD10CM/Codes/Changes/New_Codes/2?year=2018 whereas the current data comes from 2016. I will work on adding the 2019 codes soon. For comorbidity calculations, this should have no effect.
