### ISSUE TITLE
cannot install in R 3.6.3 or 3.6.1

### ISSUE THREAD

**Issue by TriciaZhai** [jackwasey/icd#200]
Hi, I am trying to process a data with ICD-10 codes. I have R 3.6.3 on PC and R 3.6.1 on Mac. I tried install.packages(), remotes::instal_github(jackwasey/icd), but cannot install on either device.
remotes::install_version("icd",3.3) will request me to choose update. No matter I update or not, it will report error and fail to install

Mac error:
 Error: (converted from warning) Setting LC_CTYPE failed, using "C"
Execution halted
Error: Failed to install 'unknown package' from URL:
  (converted from warning) installation of package 'icd.data' had non-zero exit status

PC error:
Error: unexpected symbol in "tools:::makeLazyLoading("icd.data", "C:/Users/Tricia's tower/Documents/R/win-library/3.6/00LOCK-icd.data/00new", keep.source = FALSE, keep.parse.data = FALSE, set.install.dir = 'C:/Users/Trici"
Execution halted
ERROR: lazy loading failed for package 'icd.data'
* removing 'C:/Users/Tricia's tower/Documents/R/win-library/3.6/icd.data'
Error: Failed to install 'unknown package' from URL:
  (converted from warning) installation of package ‘icd.data’ had non-zero exit status

I am not sure if I am the only one experiencing this issue. I wish you have time to look into it.

**Comment by jackwasey** [comment]
Thanks for using 'icd' and submitting this report. 'icd.data' has not been used, and deprecated for quite a while. You may need to use MRAN if you are using an old combination of R and the repositories. In addition, 9e51986bdabf4d850e17ad73935c0e3ff4c52832 is release v4.0.8 which should get 'icd' back on CRAN soon.
