### ISSUE TITLE
Confusion over undefined ICD codes

### ISSUE THREAD

**Issue by jacobcvt12** [jackwasey/icd#204]
Thanks for the great package! I'm confused about the follow:

```r
library(icd)
explain_code(c("E10"))
explain_code(c("E10", "I20"))
```

In the second line I get the following error:

```
character(0)
Warning message:
Some ICD codes are not 'defined' when trying to condense when explaining codes. Consider using warn = FALSE or condense = FALSE. Will drop these and continue. Examples: E10
```

However, the third line provides the correct explanation:
```
[1] "Type 1 diabetes mellitus" "Angina pectoris"
```

Why is E10 not being explained in the first call but is in the second? Is there any way around this issue?

**Comment by jackwasey** [comment]
Looks like the heuristics guess E... on its own is an ICD-9-CM code. I think the documentation explains how to deal with this. Try using `as.icd10(“E10”)` first, or call the S3, something like `explain_code.icd10(“E10”)`. Can’t check these answers right now.

As ICD-9 is getting older and older, I’ll think about defaulting to ICD-10. There is still a vast amount of historic ICD-9 data, though.

Always better to be explicit in reproducible research. The heuristic is for convenience.

**Comment by jacobcvt12** [comment]
Thanks @jackwasey . That fixes my issue.
