### ISSUE TITLE
"assert_data_frame" and "assert_list" errors

### ISSUE THREAD

**Issue by nancyorgan** [jackwasey/icd#91]
There is a possible missing dependency that causes "could not find function errors". For example, here are a few examples from the documentation ( ?icd_comorbid_df_to_mat and ?icd_diff_comorbid):
```
longdf <- icd_long_data(
  visit = c("a", "b", "b", "c"),
  icd9 = c("441", "4424", "443", "441")
)
cmbdf <- icd9_comorbid_elix(longdf, return_df = TRUE)
```

> Error in icd9_comorbid(x, map = icd::icd9_map_elix, short_map = TRUE,  : 
                         could not find function "assert_data_frame"

```
icd_diff_comorbid(icd10_map_elix, icd10_map_ahrq, show = FALSE)[["CHF"]]
```
> Error in icd_diff_comorbid.list(icd10_map_elix, icd10_map_ahrq, show = FALSE) : 
 could not find function "assert_list"

**Comment by jackwasey** [comment]
Thanks for the bug report. Try updating the checkmate package. I think I need to bump the required checkmate version in the DESCPRIPTION for icd. The function in question was introduced in April 2016, so I'll just have to figure out which version that is.
