### ISSUE TITLE
icd10_filter_valid vs icd9_filter_valid

### ISSUE THREAD

**Issue by nancyorgan** [jackwasey/icd#93]
Using ```icd10_filter_valid()``` on the same data as ```icd9_filter_valid()``` gives the error: 

> Error in icd10_filter_valid(data, short_code = FALSE) : 
  Assertion on 'x' failed: Must be of type 'character', not 'integer'. 

Example:

```
data = data.frame(icd = c("001.9"))

icd9_filter_valid(data)
[1] 001.9
Levels: 001.9

icd10_filter_valid(data)
Error in icd10_filter_valid(data) : 
  Assertion on 'x' failed: Must be of type 'character', not 'factor'. 

```

**Comment by jackwasey** [comment]
Thanks for catching that. I had previously deliberately prevented using numerical ICD9 codes in some cases, as there were so many ways these could be misinterpreted. Your test code generates a factor, so failed the test. I now just convert to strings before checking.

**Comment by nancyorgan** [comment]
Thanks for addressing this! 

This might be on my end, but I'm getting the same error with the test example I provided. I've tried reinstalling the package and using the modified functions from github. Thoughts? Thanks again for all your work on this package!
