### ISSUE TITLE
when checking validity of a factor of ICD codes, only the levels need to be checked

### ISSUE THREAD

**Issue by jackwasey** [jackwasey/icd#94]
Current workaround is to convert a factor to a character vector, and check each value. In large data sets, this would result in a lot of memory work, and duplicated tests for repeated factors. Best would be to check validity of each factor level, then apply that boolean vector result to the factor.

**Comment by jackwasey** [comment]
#93 led to the workaround

**Comment by nancyorgan** [comment]
This might be on my end, but I'm getting the same error with the test example I provided in #93. I've tried reinstalling the package and using the modified functions from github. Thoughts? Thanks again for all your work on this package!

```
data = data.frame(icd = c("001.9"))
icd9_filter_valid(data) #works
icd10_filter_valid(data) #does not work
```

**Comment by jackwasey** [comment]
Hmmm. I get this, using the current 'master' version:

```
> data = data.frame(icd = c("001.9"))
> icd9_filter_valid(data) # works
[1] 001.9
Levels: 001.9
> icd10_filter_valid(data) # does not work
factor(0)
Levels: 001.9
```

What do you see?

**Comment by nancyorgan** [comment]
Interesting. I just tried removing and reinstalling the package from CRAN, and got this:
```
remove.packages("icd")
install.packages("icd")
library("icd")

data = data.frame(icd = c("001.9"))

icd9_filter_valid(data) 
    [1] 001.9
    Levels: 001.9

icd10_filter_valid(data) 
    Error in icd10_filter_valid(data) : 
    Assertion on 'x' failed: Must be of type 'character', not 'factor'. 
```
I also tried using ```devtools::install_github("jackwasey/icd")``` but the install failed with a bunch of rcpp-related warnings. Is it possible I'm using the wrong version of the package?

**Comment by jackwasey** [comment]
Have you run update.packages() recently? Try that, then do the github
install. If you still get errors, please post them. Are you able to install
other rcpp packages? Windows rtools or another platform?

**Comment by nancyorgan** [comment]
Excellent, the github install works now, and that solved the problem. Thanks for bearing with me!

**Comment by jackwasey** [comment]
Everyone is doing fine without this, AFAIK.
The underlying code uses grep on the character vector or factor, which is probably optimized for either anyway.
