### ISSUE TITLE
icd_explain: outputs in unexpected order:

### ISSUE THREAD

**Issue by Ray-E-Artz** [jackwasey/icd#95]
It appears that the outputs of icd_explain are in sorted order according to the inputs, and not in the input order itself:  Example is as follows:

> icd_explain(as.icd10(c('E11.9', 'I10')))
> [1] "Type 2 diabetes mellitus without complications"
> [2] "Essential (primary) hypertension"  
> icd_explain(as.icd10(c('I10', 'E11.9')))
> [1] "Type 2 diabetes mellitus without complications"
> [2] "Essential (primary) hypertension"              

I have not tried to dig into the source code, but this behavior might be expected if the codes were being treated as factors rather than as character objects somewhere in the lookup process. If that is the case, one might have to force the codes to be interpreted as character objects, or use the reorder() function...

**Comment by edlee123** [comment]
I found this too and working on it.  icd_explain currently outputs major categories first, and then by the order of original icd data source.  In the first case you gave the explanation of I10 is the first output.

**Comment by kamilsi** [comment]
As a workaround I've been applying icd_explain, which preserve the ordering and doesn't mind the duplicates:

```
# sample data
codes_to_explain <- as.tbl(data.frame(coding = c(rep("9", 2)),
                                      code = c(rep("25010", 2))))
# wrapping up as a "tibble", since tibble always returns columns as tibbles, not
# vectors
codes_to_explain

codes_to_explain$Desc <-
  apply(codes_to_explain[, 2], 1, icd_explain, short_code = TRUE)
codes_to_explain
```

**Comment by jackwasey** [comment]
`icd_explain_table` now gives descriptions in the order of the vector (or factor) given. `icd_explain` groups codes, and finds common parents when all children are present, so order cannot be meaningfully preserved in the general case.
