### ISSUE TITLE
icd_explain: wrong  answer for some ICD10 codes

### ISSUE THREAD

**Issue by Ray-E-Artz** [jackwasey/icd#96]
Observed odd behavior with code 'E11.9' when not explicitly cast as an icd10 code, and not part of a vector containing other ICD10 codes.   Some examples follow.  (This might be considered as an awkward feature instead of as a bug.  If so, documentation examples of preferred usage to avoid such problems are suggested.)

> icd_explain('E11.9')
> [1] "Other activity involving computer technology and electronic devices"
> icd_explain(c('E11.9'))
> [1] "Other activity involving computer technology and electronic devices"
> icd_explain(as.icd10('E11.9'))
> [1] "Type 2 diabetes mellitus without complications"
> icd_explain(as.icd10(c('E11.9')))
> [1] "Type 2 diabetes mellitus without complications"
> 
> icd_explain('I10')
> [1] "Essential (primary) hypertension"
> icd_explain(c('I10'))
> [1] "Essential (primary) hypertension"
> icd_explain(as.icd10('I10'))
> [1] "Essential (primary) hypertension"
> icd_explain(as.icd10(c('I10')))
> [1] "Essential (primary) hypertension"
> 
> icd_explain(c('E11.9', 'I10'))
> [1] "Type 2 diabetes mellitus without complications"
> [2] "Essential (primary) hypertension"  
> icd_explain(as.icd10(c('E11.9', 'I10')))
> [1] "Type 2 diabetes mellitus without complications"
> [2] "Essential (primary) hypertension"

**Comment by jackwasey** [comment]
Thanks for that. 'E' and 'V' codes may be misinterpreted because they could
be ICD-9 or ICD-10. I'll look again at the logic to determine which is
which, but there are inevitable conflicts between the two namespaces when
only a single code is used. A warning could be given. When many codes are
used, which arguably is the more typical use case, the guess of ICD-9 vs
ICD-10 will be better.

**Comment by jackwasey** [comment]
Going to close this. Maybe will default to ICD-10 in future, but still a lot of people using ICD-9 data for retrospective research. If there is demand, I'll make ICD-10 the default sooner. Warning any time there is an ambiguous code would be very verbose. Could consider warning when there is no context, i.e. only ambiguous codes offered.
